apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
spec:
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: data
          image: test/clientapp
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
